version: '3.3'

services:
  return_data:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - http_proxy=$http_proxy
          - https_proxy=$http_proxy
    container_name: return_data
    env_file:
      - .env
    volumes:
      - './sources:/app:ro'
    command: "python3 app.py"

networks:
  web:
    external: true

