version: '3.3'

services:
  return_data:
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.port=80
      # Traefik上のバックエンド名を記載
      - traefik.backend=return_data
      - "traefik.frontend.rule=PathPrefixStrip:/check"
      - "traefik.frontend.redirect.regex=^(.*)/check$$"
      - "traefik.frontend.redirect.replacement=$$1/check/"
      - "traefik.frontend.rule=PathPrefixStrip:/check;ReplacePathRegex: ^/(.*) /$$1"
      - "traefik.docker.network=web"
      - "traefik.frontend.entryPoints=http"
      - "traefik.protocol=http"
